### ISSUE TITLE
Code/Design review

### ISSUE THREAD

**Issue by vsheo** [saschavanvliet/pleasurable-ui#25]
dit is de feedback vanuit Milledoni 1G

@nadiachaja

**Comment by vsheo** [comment]
## code conventies

Wat ons opvalt, is dat er nog geen codeconventies zijn vastgelegd. Het kan handig zijn om hier afspraken over te maken, zodat iedereen de code op een consistente manier schrijft. Tijdens pull requests kunnen jullie deze conventies gebruiken als basis voor review, zodat de main branch schoon en overzichtelijk blijft.

**Comment by vsheo** [comment]
## Responsive
De website is mobile-first opgebouwd met min-width media queries, wat goed is. Maar voor hele kleine schermen verschijnen horizontale scrollbars. Het is handig om ook vanaf bijvoorbeeld 320px goed te testen en te zorgen dat de layout zich daar netjes aanpast.

We zien dat jullie media queries op deze manier hebben geschreven:
https://github.com/saschavanvliet/pleasurable-ui/blob/c49e2d0ae4fe038835c2d3e1edcaaf2b39d67562/public/styles/style.css#L128-L138

De CSS-selector .nav-links li wordt nu twee keer gebruikt, maar dit kan ook gecombineerd worden tot één regel. Dat is netter én beter voor de performance van de website."

``` css
.nav-links li {
  text-align: center;
  padding: 0.5rem 0;

  @media (min-width: 769px) {
      text-align: left;
      padding: 0;
}
```
